Added setup endpoint coverage.
dev-yoonik/YK-BiT-SDK-DotNetCore pull request #5
Opened 2021-11-22 19:06 UTC by jppdpf

2021-11-22 22:09 UTC, vitormcpedro requested changes

2021-11-22 22:09 UTC, vitormcpedro commented on CHANGELOG.md
>  ### Added
Missing new line after this heading

2021-11-22 22:09 UTC, vitormcpedro commented on YooniK.BiometricInThings/YooniK.BiometricInThings.Client.Sample/Program.cs
> + *      - Restart the BiT App
No need to restart

2021-11-22 22:09 UTC, vitormcpedro commented on YooniK.BiometricInThings/YooniK.BiometricInThings.Client/Client/BiometricInThingsClient.cs
> +            catch (Exception)
this catch is not needed because it is just re-throwing the exception.

2021-11-23 12:18 UTC, mlourencoeb commented on CHANGELOG.md
> +## [Unreleased]
unreleaded not Unreleased.

2021-11-23 12:18 UTC, mlourencoeb commented on YooniK.BiometricInThings/YooniK.BiometricInThings.Client/Client/BiometricInThingsClient.cs
> +        {
Setup logic with true/false seems to ugly. if the setup does not work, just let the exception being raised.

2021-11-23 16:22 UTC, jppdpf commented on CHANGELOG.md
> +## [Unreleased]
On the keepachangelog it's capital so that is why I updated. Do I revert the changes?

2021-11-25 22:04 UTC, jppdpf commented on YooniK.BiometricInThings/YooniK.BiometricInThings.Client/Client/BiometricInThingsClient.cs
> +            catch (Exception)
All the other functions have implicit rethrow. Should I delete this one?

2021-12-06 10:45 UTC, mlourencoeb commented on YooniK.BiometricInThings/YooniK.BiometricInThings.Client/Client/BiometricInThingsClient.cs
> +            catch (Exception)
Keep the rethrow for consistency now. We will revisit later.

2021-12-06 10:46 UTC, mlourencoeb commented on CHANGELOG.md
> +## [Unreleased]
yes

2021-12-06 10:46 UTC, mlourencoeb commented on YooniK.BiometricInThings/YooniK.BiometricInThings.Client/Client/BiometricInThingsClient.cs
> +            catch (Exception)
but remove the true/false logic if not yet done.

2021-12-16 15:31 UTC, mlourencoeb approved these changes

2021-12-16 15:36 UTC, vitormcpedro approved these changes

2021-12-16 15:36 UTC, merged